// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyfbozbhmvmneglokmsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5ZmJvemJobXZtbmVnbG9rbXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTQwMzEsImV4cCI6MjA3MDU5MDAzMX0.qsL5dtemtbYmXmdi1Zff1xqrXP-Rmruug7-98rqhePQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});